# Generated by Django 5.2.14 on 2026-06-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Library",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="도서관명")),
                (
                    "address",
                    models.CharField(max_length=300, verbose_name="도로명 주소"),
                ),
                ("latitude", models.FloatField(verbose_name="위도")),
                ("longitude", models.FloatField(verbose_name="경도")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="전화번호"
                    ),
                ),
                ("homepage", models.URLField(blank=True, verbose_name="홈페이지 URL")),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="최종 동기화 시각"
                    ),
                ),
            ],
            options={
                "verbose_name": "도서관",
                "verbose_name_plural": "도서관 목록",
                "ordering": ["name"],
            },
        ),
    ]
