# Generated by Django 5.2.14 on 2026-06-03 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book_id",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="도서 ID"
                    ),
                ),
                (
                    "book_title",
                    models.CharField(max_length=500, verbose_name="도서 제목"),
                ),
                ("nickname", models.CharField(max_length=50, verbose_name="닉네임")),
                ("password", models.CharField(max_length=128, verbose_name="비밀번호")),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="별점",
                    ),
                ),
                ("comment", models.CharField(max_length=100, verbose_name="한 줄 평")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성 시각"),
                ),
            ],
            options={
                "verbose_name": "리뷰",
                "verbose_name_plural": "리뷰 목록",
                "ordering": ["-created_at"],
            },
        ),
    ]
